# Generated by Django 6.0.7 on 2026-08-16 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from sitepulse.operations import CreateHitTable


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': 'browsers',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngestHealth',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('dropped', models.BigIntegerField(default=0)),
                ('write_errors', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ingest health',
                'verbose_name_plural': 'ingest health',
                'db_table': 'sitepulse_ingest_health',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'operating system',
                'verbose_name_plural': 'operating systems',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('value', models.BinaryField(max_length=32)),
            ],
            options={
                'db_table': 'sitepulse_salt',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sitepulse_state',
            },
        ),
        migrations.CreateModel(
            name='DailyPageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b0', models.PositiveIntegerField(default=0)),
                ('b1', models.PositiveIntegerField(default=0)),
                ('b2', models.PositiveIntegerField(default=0)),
                ('b3', models.PositiveIntegerField(default=0)),
                ('b4', models.PositiveIntegerField(default=0)),
                ('b5', models.PositiveIntegerField(default=0)),
                ('b6', models.PositiveIntegerField(default=0)),
                ('b7', models.PositiveIntegerField(default=0)),
                ('b8', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('route', models.CharField(blank=True, default='', max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('is_bot', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('entries', models.PositiveIntegerField(default=0)),
                ('exits', models.PositiveIntegerField(default=0)),
                ('bounces', models.PositiveIntegerField(default=0)),
                ('total_duration_ms', models.BigIntegerField(default=0)),
                ('total_query_count', models.BigIntegerField(default=0)),
                ('total_query_ms', models.BigIntegerField(default=0)),
                ('query_sampled_views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'daily page stat',
                'db_table': 'sitepulse_daily_page',
                'indexes': [models.Index(fields=['date'], name='sitepulse_page_date')],
                'constraints': [models.UniqueConstraint(fields=('date', 'route', 'path', 'is_bot'), name='sitepulse_page_grain')],
            },
        ),
        migrations.CreateModel(
            name='DailySourceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('referrer_host', models.CharField(blank=True, default='', max_length=128)),
                ('utm_source', models.CharField(blank=True, default='', max_length=64)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=64)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=64)),
                ('is_bot', models.BooleanField(default=False)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('bounces', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'daily source stat',
                'db_table': 'sitepulse_daily_source',
                'indexes': [models.Index(fields=['date'], name='sitepulse_source_date')],
                'constraints': [models.UniqueConstraint(fields=('date', 'referrer_host', 'utm_source', 'utm_medium', 'utm_campaign', 'is_bot'), name='sitepulse_source_grain')],
            },
        ),
        migrations.CreateModel(
            name='DailyStatusStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b0', models.PositiveIntegerField(default=0)),
                ('b1', models.PositiveIntegerField(default=0)),
                ('b2', models.PositiveIntegerField(default=0)),
                ('b3', models.PositiveIntegerField(default=0)),
                ('b4', models.PositiveIntegerField(default=0)),
                ('b5', models.PositiveIntegerField(default=0)),
                ('b6', models.PositiveIntegerField(default=0)),
                ('b7', models.PositiveIntegerField(default=0)),
                ('b8', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('route', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.SmallIntegerField()),
                ('is_bot', models.BooleanField(default=False)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'daily status stat',
                'db_table': 'sitepulse_daily_status',
                'indexes': [models.Index(fields=['date'], name='sitepulse_status_date')],
                'constraints': [models.UniqueConstraint(fields=('date', 'route', 'status', 'is_bot'), name='sitepulse_status_grain')],
            },
        ),
        migrations.CreateModel(
            name='DailyUniqueVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visitor_hash', models.BinaryField(max_length=16)),
                ('is_bot', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'daily unique visitor',
                'db_table': 'sitepulse_daily_visitor',
                'constraints': [models.UniqueConstraint(fields=('date', 'visitor_hash'), name='sitepulse_visitor_grain')],
            },
        ),
        # Ordinary CreateModel everywhere except PostgreSQL, where this produces
        # a table partitioned by month on `ts`. See sitepulse/partitions.py.
        CreateHitTable(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('visitor_hash', models.BinaryField(max_length=16)),
                ('session_id', models.BinaryField(max_length=16)),
                ('is_new_session', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=255)),
                ('route', models.CharField(blank=True, default='', max_length=255)),
                ('view_name', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.SmallIntegerField(choices=[(0, 'other'), (1, 'GET'), (2, 'POST'), (3, 'PUT'), (4, 'PATCH'), (5, 'DELETE'), (6, 'HEAD'), (7, 'OPTIONS')], default=1)),
                ('status', models.SmallIntegerField()),
                ('duration_ms', models.IntegerField()),
                ('query_count', models.SmallIntegerField(blank=True, null=True)),
                ('query_ms', models.IntegerField(blank=True, null=True)),
                ('referrer_host', models.CharField(blank=True, default='', max_length=128)),
                ('referrer_path', models.CharField(blank=True, default='', max_length=255)),
                ('utm_source', models.CharField(blank=True, default='', max_length=64)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=64)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=64)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('device', models.SmallIntegerField(choices=[(0, 'other'), (1, 'desktop'), (2, 'mobile'), (3, 'tablet'), (4, 'bot')], default=0)),
                ('is_bot', models.BooleanField(default=False)),
                ('screen_w', models.SmallIntegerField(blank=True, null=True)),
                ('props', models.JSONField(blank=True, null=True)),
                ('browser', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hits', to='sitepulse.browser')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('os', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hits', to='sitepulse.operatingsystem')),
            ],
            options={
                'verbose_name': 'hit',
                'verbose_name_plural': 'hits',
                'db_table': 'sitepulse_hit',
                'permissions': [('view_dashboard', 'Can view the SitePulse dashboard')],
                'indexes': [models.Index(fields=['ts'], name='sitepulse_hit_ts'), models.Index(fields=['visitor_hash', 'ts'], name='sitepulse_hit_visitor'), models.Index(fields=['route', 'ts'], name='sitepulse_hit_route')],
            },
        ),
        migrations.CreateModel(
            name='DailyGeoDeviceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('device', models.SmallIntegerField(choices=[(0, 'other'), (1, 'desktop'), (2, 'mobile'), (3, 'tablet'), (4, 'bot')], default=0)),
                ('is_bot', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sitepulse.browser')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sitepulse.operatingsystem')),
            ],
            options={
                'verbose_name': 'daily geo/device stat',
                'db_table': 'sitepulse_daily_geo_device',
                'indexes': [models.Index(fields=['date'], name='sitepulse_geo_date')],
                'constraints': [models.UniqueConstraint(fields=('date', 'country', 'device', 'browser', 'os', 'is_bot'), name='sitepulse_geo_grain')],
            },
        ),
    ]
